CREATE DATABASE IF NOT EXISTS b1app;
USE b1app;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS files;

CREATE TABLE IF NOT EXISTS files (
  file_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  file_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS departments (
  xml_id VARCHAR(45) NOT NULL PRIMARY KEY,
  parent_xml_id VARCHAR(45) DEFAULT NULL,
  name_department VARCHAR(100) NOT NULL,
  file_id INT NOT NULL,
  FOREIGN KEY (file_id) REFERENCES files (file_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  xml_id VARCHAR(45) NOT NULL PRIMARY KEY,
  last_name VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  second_name VARCHAR(100) NOT NULL,
  department VARCHAR(45) NOT NULL,
  work_position VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  mobile_phone VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(100) DEFAULT NULL,
  login VARCHAR(100) NOT NULL,
  password VARCHAR(100) NOT NULL,
  file_id INT NOT NULL,
  FOREIGN KEY (file_id) REFERENCES files (file_id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (department) REFERENCES departments (xml_id) ON DELETE CASCADE ON UPDATE CASCADE
);